StoreService/WebStore/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WebStore.Common;
using WebStore.localhost;
using WebStore.Models;

namespace WebStore.Controllers
{
    public class CartController : BaseController
    {
        private const string CartSession = "CartSession";
        //
        // GET: /Cart/
        public ActionResult Index()
        {
            var cartItem = Session[CartSession];
            var list = new List<CartItem>();
            if (cartItem != null)
            {
                list = (List<CartItem>)cartItem;
            }
            return View(list);
        }
        public JsonResult DeleteAll()
        {
            Session[CartSession] = null;
            return Json(new
            {
                status = true
            });
        }

        public JsonResult Delete(String id)
        {
            var sessionCart = (List<CartItem>)Session[CartSession];
            sessionCart.RemoveAll(x => x.product.Id == id);
            Session[CartSession] = sessionCart;

            return Json(new
            {
                status = true
            });
        }
        public JsonResult Update(string cartModel)
        {
            var jsonCart = new JavaScriptSerializer().Deserialize<List<CartItem>>(cartModel);
            var sessionCart = (List<CartItem>)Session[CartSession];
            foreach (var item in sessionCart)
            {
                var jsonItem = jsonCart.SingleOrDefault(x => x.product.Id == item.product.Id);
                if (jsonCart != null)
                {
                    item.Quantity = jsonItem.Quantity;
                }
            }
            Session[CartSession] = sessionCart;
            return Json(new
            {
                status = true
            });
        }

        public ActionResult AddItem(String productId, int quantity)
        {
            localhost.Service service = new localhost.Service();
            var product = service.GetProductById(productId);
            var cart = Session[CartSession];
            if (cart != null)
            {
                var list = (List<CartItem>)cart;
                if (list.Exists(x => x.product.Id.Equals(product.Id)))
                {
                    foreach (var item in list)
                    {
                        if (item.product.Id.Equals(product.Id))
                        {
                            item.Quantity += quantity;
                        }
                    }
                }
                else
                {
                    // create new cart item
                    var item = new CartItem();
                    item.product = product;
                    item.Quantity = quantity;
                    list.Add(item);
                }
                // assign to session
                Session[CartSession] = list;

            }
            else
            {
                // create new cart item
                var item = new CartItem();
                item.product = product;
                item.Quantity = quantity;
                var list = new List<CartItem>();
                list.Add(item);
                // assign to session
                Session[CartSession] = list;
            }
            return RedirectToAction("Index");
        }
        public void GetCustomer()
        {
            localhost.Service service = new localhost.Service();
            List<Customer> cusList = service.GetCustomers().ToList();
            List<SelectListItem> li = new List<SelectListItem>();

            for (int i = 0; i < cusList.Count; i++)
            {
                li.Add(new SelectListItem { Text = cusList.ElementAt(i).Username, Value = cusList.ElementAt(i).Id });
            }
            ViewData["customers"] = li;
            System.Diagnostics.Debug.WriteLine("Number of customers: " + li.Count);
        }

        public ActionResult Payment()
        {
            
            var cartItem = Session[CartSession];
            var list = new List<CartItem>();
            if (cartItem != null)
            {
                list = (List<CartItem>)cartItem;
            }
            var client = (UserLogin)Session[Common.CommonConstants.Client_SESSION];
            ViewBag.clientID = client.UserID;
            return View(list);
        }

        [HttpPost]
        public ActionResult Payment(string Id, string Name, string address, string CusId)
        {
            localhost.Service service = new localhost.Service();
            var order = new WebStore.localhost.TheOrder();
            order.Id = Id;
            order.ShipAddress = address;
            order.Name = Name;
            order.CusId = CusId;
            

            try
            {

                var id = service.InsertOrder(order);
                var cartItem = (List<CartItem>)Session[CartSession];
                
                
                foreach (var item in cartItem)
                {
                    var orderDetail = new WebStore.localhost.OrderDetail();
                    orderDetail.Id = id + item.product.Id;
                    orderDetail.OrdId = id;
                    orderDetail.ProdId = item.product.Id;
                    orderDetail.Price = item.product.Price;
                    orderDetail.Quantity = item.Quantity;
                    var currentid = service.InsertOrderDetail(orderDetail);
                    
                }

            }
            catch (Exception ex)
            {
                string a = ex.Message;

                
            }

            return Redirect("Success");
        }

        public ActionResult Success()
        {
            return View();
        }
	}
}

StoreService/WebStore/Views/Cart/Index.cshtml
 @model List<WebStore.Models.CartItem>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section jsFooter{
    <script src="/Assets/Client/js/controller/cartController.js"></script>
}
<div class="content">
    <div class="content_top">

        <div class="clear"></div>
    </div>
    <div class="section group">
        @if (Model.Count() > 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>Product Code</th>
                        <th>Name</th>
                        <th>Image</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Total Price</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.product.Id</td>
                            <td>@item.product.Name</td>
                            <td><img src="~/images/laptop.jpg" width="100" alt="Image" /></td>
                            <td><input type="number" class="txtQuantity" data-id="@item.product.Id" value="@(item.Quantity>0?item.Quantity.ToString():"0")" /></td>
                            <td>@item.product.Price.GetValueOrDefault(0).ToString("N0")</td>
                            <td>@(item.Quantity > 0 ? (item.product.Price.GetValueOrDefault(0) * item.Quantity).ToString() : "0")</td>
                            <td><a href="#" class="btn-delete" data-id="@item.product.Id">Xoa</a></td>
                        </tr>
                    }

                </tbody>
            </table>

            <button id="btnContinue">Continue</button>
            <button id="btnUpdate">Update cart</button>
            <button id="btnDeleteAll">Delete Cart</button>
            <button id="btnPayment">Payment</button>
        }
        else
        {
            <span class="alert alert-danger">No existing item in the cart</span>
        }

    </div>
</div>

StoreService/WebStore/Views/Cart/Payment.cshtml
@model List<WebStore.Models.CartItem>
@{
    ViewBag.Title = "Payment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content">
    <div class="content_top">

        <div class="clear"></div>
    </div>
    <div class="section group">
        @if (Model.Count() > 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>Product Code</th>
                        <th>Name</th>
                        <th>Image</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Total Price</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.product.Id</td>
                            <td>@item.product.Name</td>
                            <td><img src="~/images/laptop.jpg" width="100" alt="Image" /></td>
                            <td><input type="number" class="txtQuantity" data-id="@item.product.Id" value="@(item.Quantity>0?item.Quantity.ToString("N0"):"0")" /></td>
                            <td>@item.product.Price.GetValueOrDefault(0).ToString("N0")</td>
                            <td>@(item.Quantity > 0 ? (item.product.Price.GetValueOrDefault(0) * item.Quantity).ToString("N0") : "0")</td>
                            <td><a href="#" class="btn-delete" data-id="@item.product.Id">Xoa</a></td>
                        </tr>
                    }

                </tbody>
            </table>
        }
    </div>

    <div class="section group">
        <div class="col-md-6">
            @using (Html.BeginForm("Payment", "Cart", FormMethod.Post))
            {
                <div class="form-group">
                    <label>Order Id</label>
                    <input name="Id" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Name</label>
                    <input name="Name" class="form-control" />
                </div>
                
                <div class="form-group">
                    <label>Address</label>
                    <input name="address" class="form-control" />
                </div>
                <div class="form-group">
                    @*<label>Customer</label>*@
                    <input name="CusId" value="@(ViewBag.clientID)" type="hidden" class="form-control" />
                    
                </div>
                <button type="submit" class="btn btn-success">send order</button>
            }
        </div>
    </div>
</div>

StoreService/WebStore/Views/Cart/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="alert alert-success">
    purchased successfully
</div>